import Image from "next/image";
import Link from "next/link";

const solutions = [
  { number: "01", title: "Waste Collection & Handling", body: "Scheduled collection and responsible handling designed around each site's waste profile and operating needs.", image: "/waste-truck.webp" },
  { number: "02", title: "Compliance Support", body: "Practical procedures, documentation and traceability support to help teams manage waste responsibly.", image: "/IMG-20250526-WA0022.jpg" },
  { number: "03", title: "Segregation & Recovery", body: "Segregation at source, recyclable-material separation and recovery pathways that reduce disposal.", image: "/IMG-20250526-WA0017.jpg" },
  { number: "04", title: "Circularity & ESG Support", body: "Staff sensitisation, reduction initiatives and waste-performance evidence for continuous improvement.", image: "/IMG-20250526-WA0020.jpg" },
];
const sectors = ["Manufacturing & Industrial", "Hotels & Hospitality", "Commercial Property", "Corporate Offices", "Education & Institutions", "Residential Developments"];

export default function Home() {
  return <>
    <section className="corporate-hero"><div className="hero-image"><Image src="/worker-residential.webp" alt="Pearl Eco Solutions team member at work" fill priority style={{ objectFit: "cover" }} /><div className="hero-overlay" /></div><div className="wrap hero-content"><p className="hero-kicker">Integrated waste management & environmental solutions · Kenya</p><h1>From waste collection to <em>compliance</em> and circularity.</h1><p className="hero-copy">Helping organisations manage waste responsibly, recover value, improve visibility and build more circular operations.</p><div className="hero-actions"><Link href="/contact" className="btn-primary">Request a site assessment</Link><Link href="/services" className="btn-outline-white">Explore our solutions</Link></div><div className="hero-stats"><div><strong>10+</strong><span>Years of operating experience</span></div><div><strong>50+</strong><span>Local jobs created</span></div><div><strong>3</strong><span>Waste streams at collection</span></div><div><strong>Kenya</strong><span>Community-rooted delivery</span></div></div></div></section>
    <section className="section corporate-intro"><div className="wrap two-col-start"><div><p className="eyebrow">Who we are</p><h2>A practical environmental partner for organisations.</h2><p>Pearl Eco Solutions is an integrated waste management and environmental solutions partner helping businesses move from responsible waste collection to waste compliance and circularity.</p><p>Established in 2012, we have grown from a cleaning and waste collection business into a broader environmental and facility-services enterprise serving corporate offices, institutions, commercial properties, hospitality establishments, residential developments and industrial sites.</p><Link href="/about" className="text-link">Discover our story →</Link></div><div className="positioning-card"><p className="eyebrow">Our corporate promise</p><h3>Reliable service delivery. Responsible waste management. Practical environmental improvement.</h3><div className="journey-line"><span>Collect</span><span>Comply</span><span>Recover</span><span>Measure</span><span>Improve</span></div></div></div></section>
    <section className="section solution-section"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">Our solutions</p><h2>Build better waste systems, one practical step at a time.</h2></div><Link href="/services" className="btn-outline">View all solutions</Link></div><div className="solution-grid">{solutions.map((s) => <article className="solution-card" key={s.number}><div className="solution-image"><Image src={s.image} alt={s.title} fill style={{ objectFit: "cover" }} /><span>{s.number}</span></div><div><h3>{s.title}</h3><p>{s.body}</p></div></article>)}</div></div></section>
    <section className="section sector-section"><div className="wrap two-col-start"><div><p className="eyebrow">Industries we serve</p><h2>Designed around the realities of your site.</h2><p>We scope solutions around the waste profile, operating requirements, service priorities and improvement goals of each client.</p><Link href="/contact" className="btn-primary">Start a conversation</Link></div><div className="sector-grid">{sectors.map((sector) => <div key={sector}>{sector}<span>↗</span></div>)}</div></div></section>
    <section className="corporate-cta"><div className="wrap cta-row"><div><p className="eyebrow light">Let&apos;s understand your waste</p><h2>Ready to strengthen your waste operations?</h2><p>Whether you need better collection, segregation, recovery or reporting, we can help identify a practical pathway.</p></div><Link href="/contact" className="btn-light">Request a corporate assessment</Link></div></section>
  </>;
}
